backend:
  name: github
  repo: Broken-Mentat/aprender-blog  # GitHub username and repo
  branch: main
  auth_endpoint: api/auth  # for GitHub OAuth via Cloudflare Pages

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
